const resData = [
    {
        id: 1,
        aa: '张三',
        bb: '18258261040',
        cc: 1,
        dd: true,
        ee: 1,
        ff: 1,
        gg: '2024-01',
        hh: 1,
    },
    {
        id: 2,
        aa: '李四',
        bb: '18258261041',
        cc: 2,
        dd: false,
        ee: 2,
        ff: 2,
        gg: null,
        hh: 1,
    },
    {
        id: 3,
        aa: '王五',
        bb: '18258261042',
        cc: 3,
        dd: true,
        ee: 3,
        ff: 3,
        gg: null,
        hh: 2,
    },
    {
        id: 4,
        aa: '赵六',
        bb: null,
        cc: 1,
        dd: null,
        ee: 4,
        ff: 4,
        gg: null,
        hh: 2,
    },
];

export { resData };
